import DevToolsLocalization
import TemplateLocalization
import TemplateDesignSystem

typealias AppColors = TemplateDesignSystemAsset.Colors
typealias AppImages = TemplateDesignSystemAsset.Images
typealias AppStrings = TemplateLocalization
typealias AppLocalization = RuntimeLocalization
typealias AppLocalizationObserver = RuntimeLocalizationObserver
typealias AppLocalizedPreview = RuntimeLocalizedPreview
